package com.cts.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Question")
public class Question
{
    private String id;

    private Term who;
    private Term what;
    private Term where;

    public Term getWho()
    {
        return who;
    }

    public void setWho(Term who)
    {
        this.who = who;
    }

    public Term getWhat()
    {
        return what;
    }

    public void setWhat(Term what)
    {
        this.what = what;
    }

    public Term getWhere()
    {
        return where;
    }

    public void setWhere(Term where)
    {
        this.where = where;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    @Override
    public String toString()
    {
        return "Question{" +
            "id='" + id + '\'' +
            ", who=" + who +
            ", what=" + what +
            ", where=" + where +
            '}';
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof Question)) return false;

        Question question = (Question) o;

        return id != null ? id.equals(question.id) : question.id == null;
    }

    @Override
    public int hashCode()
    {
        return id != null ? id.hashCode() : 0;
    }
}
